version: 2.1

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - main

jobs:
  build:
    working_directory: ~/Simple_Application
    docker:
      - image: circleci/node:16  # Updated Node.js version
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@8'
      - run:
          name: Clear npm cache
          command: npm cache clean --force
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies
          command: npm install
      # - run:
      #     name: Run tests
      #     command: npm run test
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: docker-login
          command: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - run:
          name: Build Docker Image
          command: docker build -t $IMAGE_APP:latest .
      - run:
          name: Publish Docker Image
          command: docker push $IMAGE_APP
      # Persisting the private key (if needed)
      - run:
          name: Get Login Key
          command: echo "$CON_KEY" > logkey.pem
      - run:
          name: Change rights of pem file
          command: chmod 600 logkey.pem
      - persist_to_workspace:
          root: .
          paths:
            - logkey.pem  # Ensure the key file is available in the deploy job

  deploy:
    docker:
      - image: circleci/node:16
    steps:
      # Attaching the workspace to the deploy job to access the logkey.pem
      - attach_workspace:
          at: /workspace
      - run:
          name: Deploy application
          command: |
            # Using the private key for SSH
            ssh -o StrictHostKeyChecking=no -i /workspace/logkey.pem $EC2_USERNAME@$EC2_PUBLIC_DNS "
            export SERVER='$SERVER' PRIVATE_KEY='$PRIVATE_KEY' && \
            rm -rf Simple_Application/ && \
            git clone https://github.com/CraigReddinNCI/Simple_Application.git && \
            bash Simple_Application/deploy.sh"
