version: 2.1

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - main

jobs:
  build:
    working_directory: ~/Simple_Application
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@8'
      - run:
          name: Clear npm cache
          command: npm cache clean --force
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Npm Autdit
          command: npm audit || true
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: docker-login
          command: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - run:
          name: Build Docker Image
          command: docker build --no-cache --build-arg SERVER_CRT="$SERVER" --build-arg PRIVATE_KEY="$PRIVATE_KEY" -t $IMAGE_APP:latest .

      - run:
          name: Publish Docker Image
          command: docker push $IMAGE_APP

  deploy:
    docker:
      - image: circleci/node:16
    steps:
      
      - run:
          name: Deploy application
          #comment for repo pushes
          command: |
            ssh -o StrictHostKeyChecking=no $EC2_USERNAME@$EC2_PUBLIC_DNS "
            export SERVER='$SERVER' PRIVATE_KEY='$PRIVATE_KEY' IMAGE_APP='$IMAGE_APP' && \
            sudo docker pull $IMAGE_APP:latest && \
            bash Simple_Application/deploy.sh"
